import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModalProvider } from "@/components/providers/model-provider";

const font = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className)}>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} storageKey="unreast-theme">
            {children}
            <ModalProvider/>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
